#!/bin/bash

#brc=$(grep "~/diary.sh" ~/.bashrc)
#if [ -z "$brc" ]
#  then echo "source ~/diary.sh" >> .bashrc
#fi

#echo ls -d */ | cut -f1 -d'/

re='^[0-9]+$'

read yournumber    
while ! [[  $yournumber =~ $re &&  $yournumber -le 10  &&  $yournumber -ge 1 ]]
do
	echo "error: Not a number"
	read yournumber
done	

cd $DIARY_PATH
    printf "Введите название файла: "
    read file
    if [[ "${file: -3}" != ".md" ]]; then file="$file.md"
    fi
    flag=0
    for year in "$DIARY_PATH"/*
    do
        for month in "$year"/*
        do
	    l=$month/$file
            if [ -e $l ];
            then
                flag=1
            fi
        done
    done
    if [ "$flag" == "0" ]
	then 
	    echo "$file не найден"
	else 
	    cd ${file:4:4}
    	    cd ${MONTHS[${file:9:2}-1]}
    	    cp $file $DIARY_PATH/корзина
    	    rm $file
    fi 
    
    
templatePath=$DIARY_PATH/шаблоны/$file
    if [ ! -e $templatePath ]
    then
        echo $templatePath не найден
    else
        cd $DIARY_PATH/шаблоны/       
        cp $file $DIARY_PATH/$(date +%Y)/$(date +%B)/
        cd /
        cd $DIARY_PATH/$(date +%Y)/$(date +%B)/
        mv $file ID__$(date +"%F_%H-%M").md
	exec $EDITOR ID__$(date +"%F_%H-%M").md
    fi	    
